### ISSUE TITLE
Component doesn't format an retrieved frequency

### ISSUE THREAD

**Issue by edvmorango** [rvalenciano/angular2-cron-jobs#6]
When I set my ngModel.frequency from a JSON the component receive the values, but doesn't render nothing, is there a way to do this?

**Comment by rvalenciano** [comment]
Hi, currently I'm refactoring a bit the library to a more appropriate format as library.  As soon I finish this I'll dive into this.

**Comment by edvmorango** [comment]
Okay @rvalenciano thank you.
